language: cpp
compiler:
  - gcc
env:
  - PARAM_THREADS="--enable-threads --with-working-c-locale"
    CXXFLAGS=""
  - PARAM_THREADS="--enable-threads --with-working-locale"
    CXXFLAGS=""
  - PARAM_THREADS="--enable-threads --with-working-c-locale"
    CXXFLAGS="-DUNICODE"
  - PARAM_THREADS="--enable-threads --with-working-locale"
    CXXFLAGS="-DUNICODE"
  - PARAM_THREADS="--disable-threads --with-working-locale"
    CXXFLAGS=""
  - PARAM_THREADS="--disable-threads --with-working-locale"
    CXXFLAGS="-DUNICODE"
  - PARAM_THREADS="--enable-threads --with-iconv"
    CXXFLAGS=""
  - PARAM_THREADS="--enable-threads --with-iconv"
    CXXFLAGS="-DUNICODE"
  - PARAM_THREADS="--disable-threads --with-iconv"
    CXXFLAGS=""
  - PARAM_THREADS="--disable-threads --with-iconv"
    CXXFLAGS="-DUNICODE"
before_install:
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo add-apt-repository --yes
    'deb http://ppa.launchpad.net/canonical-x/x-staging/ubuntu precise main'
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -q
    gcc-4.8
    g++-4.8
    libstdc++-4.8-dev
    llvm-3.4
    clang-3.4
    swig
    python
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40
    --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - sudo update-alternatives --config gcc
before_script:
  - sh ./scripts/fix-timestamps.sh
  - mkdir objdir
  - cd objdir
script: ../configure $PARAM_THREADS
  CXXFLAGS="$CXXFLAGS"
  SWIG_FLAGS="$SWIG_FLAGS"
  && make
after_failure:
  - cat config.log
  - cat tests/testsuite.log
branches:
  only:
    - 1.1.x
notifications:
  recipients:
    - vhaisman@gmail.com
  email:
    on_success: always
    on_failure: always
