//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: client.proto
namespace client
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBVector")]
  public partial class PBVector : global::ProtoBuf.IExtensible
  {
    public PBVector() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBVector2D")]
  public partial class PBVector2D : global::ProtoBuf.IExtensible
  {
    public PBVector2D() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterGameReq")]
  public partial class EnterGameReq : global::ProtoBuf.IExtensible
  {
    public EnterGameReq() {}
    
    private uint _userId = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterGameAck")]
  public partial class EnterGameAck : global::ProtoBuf.IExtensible
  {
    public EnterGameAck() {}
    
    private uint _errorCode = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private client.PBVector2D _pos = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public client.PBVector2D pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private uint _fireAngle = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"fireAngle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fireAngle
    {
      get { return _fireAngle; }
      set { _fireAngle = value; }
    }
    private uint _flyAngle = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"flyAngle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint flyAngle
    {
      get { return _flyAngle; }
      set { _flyAngle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlaneMoveReq")]
  public partial class PlaneMoveReq : global::ProtoBuf.IExtensible
  {
    public PlaneMoveReq() {}
    
    private client.PBVector2D _newPos = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"newPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public client.PBVector2D newPos
    {
      get { return _newPos; }
      set { _newPos = value; }
    }
    private uint _fireAngle = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fireAngle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fireAngle
    {
      get { return _fireAngle; }
      set { _fireAngle = value; }
    }
    private uint _flyAngle = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"flyAngle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint flyAngle
    {
      get { return _flyAngle; }
      set { _flyAngle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlaneMoveAck")]
  public partial class PlaneMoveAck : global::ProtoBuf.IExtensible
  {
    public PlaneMoveAck() {}
    
    private uint _errorCode = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private client.PBVector2D _realPos = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"realPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public client.PBVector2D realPos
    {
      get { return _realPos; }
      set { _realPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryPathReq")]
  public partial class QueryPathReq : global::ProtoBuf.IExtensible
  {
    public QueryPathReq() {}
    
    private client.PBVector _startPos = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"startPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public client.PBVector startPos
    {
      get { return _startPos; }
      set { _startPos = value; }
    }
    private client.PBVector _endPos = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"endPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public client.PBVector endPos
    {
      get { return _endPos; }
      set { _endPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryPathAck")]
  public partial class QueryPathAck : global::ProtoBuf.IExtensible
  {
    public QueryPathAck() {}
    
    private readonly global::System.Collections.Generic.List<client.PBVector> _path = new global::System.Collections.Generic.List<client.PBVector>();
    [global::ProtoBuf.ProtoMember(1, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<client.PBVector> path
    {
      get { return _path; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBObject")]
  public partial class PBObject : global::ProtoBuf.IExtensible
  {
    public PBObject() {}
    
    private uint _objId = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"objId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint objId
    {
      get { return _objId; }
      set { _objId = value; }
    }
    private client.ObjectType _type = client.ObjectType.PLANE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(client.ObjectType.PLANE)]
    public client.ObjectType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private client.PBVector2D _pos = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public client.PBVector2D pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private float _speed = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private uint _fireAngle = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fireAngle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fireAngle
    {
      get { return _fireAngle; }
      set { _fireAngle = value; }
    }
    private uint _flyAngle = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"flyAngle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint flyAngle
    {
      get { return _flyAngle; }
      set { _flyAngle = value; }
    }
    private client.ObjectStatus _status = client.ObjectStatus.ALIVE;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(client.ObjectStatus.ALIVE)]
    public client.ObjectStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlaneShootReq")]
  public partial class PlaneShootReq : global::ProtoBuf.IExtensible
  {
    public PlaneShootReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlaneShootAck")]
  public partial class PlaneShootAck : global::ProtoBuf.IExtensible
  {
    public PlaneShootAck() {}
    
    private uint _errorCode = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyObjs")]
  public partial class NotifyObjs : global::ProtoBuf.IExtensible
  {
    public NotifyObjs() {}
    
    private readonly global::System.Collections.Generic.List<client.PBObject> _objList = new global::System.Collections.Generic.List<client.PBObject>();
    [global::ProtoBuf.ProtoMember(1, Name=@"objList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<client.PBObject> objList
    {
      get { return _objList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBCollisionPair")]
  public partial class PBCollisionPair : global::ProtoBuf.IExtensible
  {
    public PBCollisionPair() {}
    
    private uint _objId = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"objId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint objId
    {
      get { return _objId; }
      set { _objId = value; }
    }
    private uint _targetId = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyCollision")]
  public partial class NotifyCollision : global::ProtoBuf.IExtensible
  {
    public NotifyCollision() {}
    
    private client.PBCollisionPair _collisionList = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"collisionList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public client.PBCollisionPair collisionList
    {
      get { return _collisionList; }
      set { _collisionList = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ClientProtocol")]
    public enum ClientProtocol
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_GAME", Value=2000)]
      REQ_ENTER_GAME = 2000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PLANE_MOVE", Value=2001)]
      REQ_PLANE_MOVE = 2001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_PLANE_SHOOT", Value=2003)]
      REQ_PLANE_SHOOT = 2003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NTY_OBJS", Value=2004)]
      NTY_OBJS = 2004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NTY_COLLISION", Value=2005)]
      NTY_COLLISION = 2005
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LoginError")]
    public enum LoginError
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MoveType")]
    public enum MoveType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVE_LEFT", Value=1)]
      MOVE_LEFT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVE_RIGHT", Value=2)]
      MOVE_RIGHT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVE_UP", Value=3)]
      MOVE_UP = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVE_DOWN", Value=4)]
      MOVE_DOWN = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TURN_AROUND", Value=5)]
      TURN_AROUND = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ObjectType")]
    public enum ObjectType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLANE", Value=1)]
      PLANE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BULLET", Value=2)]
      BULLET = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ObjectStatus")]
    public enum ObjectStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALIVE", Value=1)]
      ALIVE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DESTROY", Value=2)]
      DESTROY = 2
    }
  
}