//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: slither_client.proto
namespace slither
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBVector2D")]
  public partial class PBVector2D : global::ProtoBuf.IExtensible
  {
    public PBVector2D() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBFood")]
  public partial class PBFood : global::ProtoBuf.IExtensible
  {
    public PBFood() {}
    
    private uint _foodId = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"foodId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint foodId
    {
      get { return _foodId; }
      set { _foodId = value; }
    }
    private slither.PBVector2D _pos = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public slither.PBVector2D pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private uint _mass = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mass", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mass
    {
      get { return _mass; }
      set { _mass = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBSnakeHead")]
  public partial class PBSnakeHead : global::ProtoBuf.IExtensible
  {
    public PBSnakeHead() {}
    
    private slither.PBVector2D _pos = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public slither.PBVector2D pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private uint _angle = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private float _radius = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"radius", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float radius
    {
      get { return _radius; }
      set { _radius = value; }
    }
    private float _speed = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBSnakeBody")]
  public partial class PBSnakeBody : global::ProtoBuf.IExtensible
  {
    public PBSnakeBody() {}
    
    private uint _bodyId = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bodyId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint bodyId
    {
      get { return _bodyId; }
      set { _bodyId = value; }
    }
    private slither.PBVector2D _pos = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public slither.PBVector2D pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBSnake")]
  public partial class PBSnake : global::ProtoBuf.IExtensible
  {
    public PBSnake() {}
    
    private uint _snakeId = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"snakeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint snakeId
    {
      get { return _snakeId; }
      set { _snakeId = value; }
    }
    private slither.PBSnakeHead _snakeHead = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"snakeHead", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public slither.PBSnakeHead snakeHead
    {
      get { return _snakeHead; }
      set { _snakeHead = value; }
    }
    private readonly global::System.Collections.Generic.List<slither.PBSnakeBody> _snakeBody = new global::System.Collections.Generic.List<slither.PBSnakeBody>();
    [global::ProtoBuf.ProtoMember(3, Name=@"snakeBody", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<slither.PBSnakeBody> snakeBody
    {
      get { return _snakeBody; }
    }
  
    private slither.PBObjectStatus _status = slither.PBObjectStatus.EXIST;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(slither.PBObjectStatus.EXIST)]
    public slither.PBObjectStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    private bool _speedUp = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"speedUp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool speedUp
    {
      get { return _speedUp; }
      set { _speedUp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterGameReq")]
  public partial class EnterGameReq : global::ProtoBuf.IExtensible
  {
    public EnterGameReq() {}
    
    private uint _userId = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterGameAck")]
  public partial class EnterGameAck : global::ProtoBuf.IExtensible
  {
    public EnterGameAck() {}
    
    private uint _errorCode = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private slither.PBSnake _snake = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"snake", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public slither.PBSnake snake
    {
      get { return _snake; }
      set { _snake = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SnakeMoveReq")]
  public partial class SnakeMoveReq : global::ProtoBuf.IExtensible
  {
    public SnakeMoveReq() {}
    
    private float _newAngle = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"newAngle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float newAngle
    {
      get { return _newAngle; }
      set { _newAngle = value; }
    }
    private bool _speedUp = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"speedUp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool speedUp
    {
      get { return _speedUp; }
      set { _speedUp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SnakeMoveAck")]
  public partial class SnakeMoveAck : global::ProtoBuf.IExtensible
  {
    public SnakeMoveAck() {}
    
    private uint _errorCode = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BroadcastMove")]
  public partial class BroadcastMove : global::ProtoBuf.IExtensible
  {
    public BroadcastMove() {}
    
    private slither.PBSnake _snakeInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"snakeInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public slither.PBSnake snakeInfo
    {
      get { return _snakeInfo; }
      set { _snakeInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BroadcastEat")]
  public partial class BroadcastEat : global::ProtoBuf.IExtensible
  {
    public BroadcastEat() {}
    
    private uint _snakeId = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"snakeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint snakeId
    {
      get { return _snakeId; }
      set { _snakeId = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _eatenFoodList = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"eatenFoodList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> eatenFoodList
    {
      get { return _eatenFoodList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BroadcastNewFood")]
  public partial class BroadcastNewFood : global::ProtoBuf.IExtensible
  {
    public BroadcastNewFood() {}
    
    private readonly global::System.Collections.Generic.List<slither.PBFood> _foodList = new global::System.Collections.Generic.List<slither.PBFood>();
    [global::ProtoBuf.ProtoMember(1, Name=@"foodList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<slither.PBFood> foodList
    {
      get { return _foodList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BroadcastCollide")]
  public partial class BroadcastCollide : global::ProtoBuf.IExtensible
  {
    public BroadcastCollide() {}
    
    private slither.PBSnake _collideSnake = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"collideSnake", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public slither.PBSnake collideSnake
    {
      get { return _collideSnake; }
      set { _collideSnake = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyGrids")]
  public partial class NotifyGrids : global::ProtoBuf.IExtensible
  {
    public NotifyGrids() {}
    
    private readonly global::System.Collections.Generic.List<slither.PBFood> _foodList = new global::System.Collections.Generic.List<slither.PBFood>();
    [global::ProtoBuf.ProtoMember(1, Name=@"foodList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<slither.PBFood> foodList
    {
      get { return _foodList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ClientProtocol")]
    public enum ClientProtocol
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ENTER_GAME", Value=2000)]
      REQ_ENTER_GAME = 2000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_MOVE", Value=2001)]
      REQ_MOVE = 2001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BROADCAST_MOVE", Value=2002)]
      BROADCAST_MOVE = 2002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BROADCAST_EAT", Value=2003)]
      BROADCAST_EAT = 2003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BROADCAST_COLLIDE", Value=2004)]
      BROADCAST_COLLIDE = 2004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BROADCAST_NEWFOODS", Value=2005)]
      BROADCAST_NEWFOODS = 2005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BROADCAST_NEWTAIL", Value=2006)]
      BROADCAST_NEWTAIL = 2006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTIFY_GRIDS", Value=2007)]
      NOTIFY_GRIDS = 2007
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ClientError")]
    public enum ClientError
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PBObjectType")]
    public enum PBObjectType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOOD", Value=1)]
      FOOD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SNAKE_HEAD", Value=2)]
      SNAKE_HEAD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SNAKE_BODY", Value=3)]
      SNAKE_BODY = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PBObjectStatus")]
    public enum PBObjectStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXIST", Value=0)]
      EXIST = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DESTROY", Value=1)]
      DESTROY = 1
    }
  
}