//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: login.proto
namespace login
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginReq")]
  public partial class LoginReq : global::ProtoBuf.IExtensible
  {
    public LoginReq() {}
    
    private string _userName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _passwd = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"passwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string passwd
    {
      get { return _passwd; }
      set { _passwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginAck")]
  public partial class LoginAck : global::ProtoBuf.IExtensible
  {
    public LoginAck() {}
    
    private uint _errorCode = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private uint _loginToken = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"loginToken", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint loginToken
    {
      get { return _loginToken; }
      set { _loginToken = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterReq")]
  public partial class RegisterReq : global::ProtoBuf.IExtensible
  {
    public RegisterReq() {}
    
    private string _userName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _passwd = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"passwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string passwd
    {
      get { return _passwd; }
      set { _passwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterAck")]
  public partial class RegisterAck : global::ProtoBuf.IExtensible
  {
    public RegisterAck() {}
    
    private uint _errorCode = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"LoginProtocol")]
    public enum LoginProtocol
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_LOGIN", Value=1000)]
      REQ_LOGIN = 1000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_REGISTER", Value=1001)]
      REQ_REGISTER = 1001
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LoginError")]
    public enum LoginError
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_SUCCESS", Value=0)]
      LOGIN_SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_NOT_EXIST", Value=1)]
      USER_NOT_EXIST = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PASSWD_ERROR", Value=2)]
      PASSWD_ERROR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_HAS_REGISTER", Value=3)]
      USER_HAS_REGISTER = 3
    }
  
}